SCREEN_HEIGHT = 720 // 1
SCREEN_WIDTH = 1280 // 1

USER_EVENT_MOVE_UP    = 1
USER_EVENT_MOVE_DOWN  = 2
USER_EVENT_MOVE_RIGHT = 3
USER_EVENT_MOVE_LEFT  = 4

USER_EVENT_START_MOVING_UP         = 5
USER_EVENT_START_MOVING_UP_RIGHT   = 6
USER_EVENT_START_MOVING_RIGHT      = 7
USER_EVENT_START_MOVING_DOWN_RIGHT = 8
USER_EVENT_START_MOVING_DOWN       = 9
USER_EVENT_START_MOVING_DOWN_LEFT  = 10
USER_EVENT_START_MOVING_LEFT       = 11
USER_EVENT_START_MOVING_UP_LEFT    = 12
USER_EVENT_STOP_MOVING             = 13

USER_EVENT_ROTATE_CW  = 14
USER_EVENT_ROTATE_CCW = 15

USER_EVENT_START_ROTATING_CW  = 16
USER_EVENT_START_ROTATING_CCW = 17
USER_EVENT_STOP_ROTATING      = 18

USER_EVENT_SHOOT      = 19
USER_EVENT_JOIN       = 20
