SCREEN_HEIGHT = 720 // 1
SCREEN_WIDTH = 1280 // 1

USER_EVENT_MOVE_UP    = 1
USER_EVENT_MOVE_DOWN  = 2
USER_EVENT_MOVE_RIGHT = 3
USER_EVENT_MOVE_LEFT  = 4
USER_EVENT_ROTATE_CW  = 5
USER_EVENT_ROTATE_CCW = 6
USER_EVENT_SHOOT      = 7
USER_EVENT_JOIN       = 8
