POST http://localhost:8000/api/events
Content-Type: application/json

{
    "player_id": "fran",
    "event": 20,
    "lang": "csharp"
}

###

POST http://localhost:8000/events
Content-Type: application/json

{
    "player_id": "zan",
    "event": 19
}

###

POST http://localhost:8000/events
Content-Type: application/json

{
    "player_id": "zan",
    "event": 13,
    "lang": "clojure"
}