services:
  codecon-message-broker:
    image: codecon-message-broker
    container_name: codecon-message-broker
    build:
      context: ../message-broker
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "15672"
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 1s
      timeout: 1s
      retries: 10

  codecon-ui:
    image: codecon-ui
    container_name: codecon-ui
    build:
      context: ../ui
      dockerfile: Dockerfile
    expose:
      - "8001"
    ports:
      - "8001:8000"
    depends_on:
      - codecon-api

  codecon-api:
    image: codecon-api
    container_name: codecon-api
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=codecon-message-broker
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    expose:
      - "8002"
    ports:
      - "8002:8000"
    depends_on:
      codecon-message-broker:
        condition: service_healthy

  codecon-routing:
    image: codecon-routing
    container_name: codecon-routing
    build:
      context: ../routing
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - codecon-ui
      - codecon-api

  codecon-game:
    image: codecon-game
    container_name: codecon-game
    build:
      context: ../game
      dockerfile: Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - RABBITMQ_HOST=codecon-message-broker
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      codecon-message-broker:
        condition: service_healthy

networks:
  default:
    driver: bridge
