services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: codecon-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "15672"
      - "5672"
    ports:
      - "15672:15672"
      - "5672:5672"

  codecon-ui:
    image: codecon-ui
    container_name: codecon-ui
    build:
      context: ../ui
      dockerfile: Dockerfile
    expose:
      - "8001"
    ports:
      - "8001:8000"
    depends_on:
      - codecon-api

  codecon-api:
    image: codecon-api
    container_name: codecon-api
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=codecon-rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
    expose:
      - "8002"
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq

  codecon-routing:
    image: codecon-routing
    container_name: codecon-routing
    build:
      context: ../routing
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - codecon-ui
      - codecon-api

networks:
  default:
    driver: bridge
